version: '3.9'
services:
  db-main:
    image: postgres:14-alpine
    container_name: db-main
    env_file:
      - env/.env.development
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - DATABASE_URL=${DATABASE_URL}
      - TZ=GMT
      - PGTZ=GMT
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata-main:/var/lib/postgresql/data
      - ./scripts/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    networks:
      - main-network

volumes:
  pgdata-main:
    driver: local

networks:
  main-network:
    name: main-network
    driver: bridge
